/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZzkjMB53QkY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex flex-col h-[90vh] max-w-md mx-auto bg-white dark:bg-gray-950 rounded-2xl shadow-lg overflow-hidden">
      <header className="bg-gray-100 dark:bg-gray-900 px-4 py-3 flex items-center gap-3">
        <Avatar className="w-8 h-8">
          <AvatarImage alt="Chatbot" src="/placeholder-user.jpg" />
          <AvatarFallback>CB</AvatarFallback>
        </Avatar>
        <div className="text-sm font-medium">Chatbot</div>
      </header>
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        <div className="flex items-start gap-3">
          <Avatar className="w-8 h-8">
            <AvatarImage alt="User" src="/placeholder-user.jpg" />
            <AvatarFallback>JP</AvatarFallback>
          </Avatar>
          <div className="bg-gray-100 dark:bg-gray-800 px-4 py-3 rounded-2xl max-w-[70%]">
            <p className="text-sm">Hi there! How can I help you today?</p>
          </div>
        </div>
        <div className="flex items-start gap-3 justify-end">
          <div className="bg-blue-500 text-white px-4 py-3 rounded-2xl max-w-[70%]">
            <p className="text-sm">I'm looking for information on your product pricing.</p>
          </div>
          <Avatar className="w-8 h-8">
            <AvatarImage alt="Chatbot" src="/placeholder-user.jpg" />
            <AvatarFallback>CB</AvatarFallback>
          </Avatar>
        </div>
        <div className="flex items-start gap-3">
          <Avatar className="w-8 h-8">
            <AvatarImage alt="User" src="/placeholder-user.jpg" />
            <AvatarFallback>JP</AvatarFallback>
          </Avatar>
          <div className="bg-gray-100 dark:bg-gray-800 px-4 py-3 rounded-2xl max-w-[70%]">
            <p className="text-sm">Great, I'd love to learn more about your pricing options.</p>
          </div>
        </div>
        <div className="flex items-start gap-3 justify-end">
          <div className="bg-blue-500 text-white px-4 py-3 rounded-2xl max-w-[70%]">
            <p className="text-sm">
              Our pricing starts at $9 per month for the basic plan. Let me know if you have any other questions!
            </p>
          </div>
          <Avatar className="w-8 h-8">
            <AvatarImage alt="Chatbot" src="/placeholder-user.jpg" />
            <AvatarFallback>CB</AvatarFallback>
          </Avatar>
        </div>
      </div>
      <div className="bg-gray-100 dark:bg-gray-900 px-4 py-3 flex items-center gap-2">
        <Input className="flex-1 bg-transparent" placeholder="Type your message..." type="text" />
        <Button className="text-blue-500" size="icon" variant="ghost">
          <SendIcon className="w-5 h-5" />
        </Button>
      </div>
    </div>
  )
}

function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
